### ISSUE TITLE
Add support for Next.js router

### ISSUE THREAD

**Issue by ViktorQvarfordt** [xiel/use-location-state#117]
It would be great to be able to use the query params through the Next.js router.

**Comment by xiel** [comment]
@ViktorQvarfordt Good suggestion, I will check and try to add it soon.

**Comment by ViktorQvarfordt** [comment]
After some further thinking, this may be tricky since Next.js uses query params for routing. We may go for the url hash approach instead. Please let me know where you land when you start looking into this!

**Comment by xiel** [comment]
Hey @ViktorQvarfordt,

by default, next js does not seem to process the query string at all, but you can access them, when you add `async function getServerSideProps()`. This is also required to make useRouter.query available during SSR. (otherwise pages are statically prerendered, so they can not know about the query string).

I prefer query params in most cases (thinking about switching to them as a new default in future versions too...) and I think it is also okay to share them with next, in some cases it might even be very useful.

The lib has a undocumented third parameter (where you can pass the interface to use to get/set the query string), so I was able to quickly put a working demo together:
https://codesandbox.io/s/github/xiel/use-location-state/tree/nextjs/src/examples/nextjs?file=/pages/index.js

Please feel free to try it out and let me know if you find problems.
– Felix


#### useNextQueryState.js
```js
import { useRouter } from 'next/router'
import { useQueryState } from 'use-location-state'

export function useNextQueryState(key, defaultValue) {
  const router = useRouter()
  return useQueryState(key, defaultValue, {
    queryStringInterface: {
      getQueryString: () => router.asPath.split('?')[1],
      setQueryString: (newQueryString, { method = 'replace' }) => {
        router[method](router.pathname + '?' + newQueryString)
      },
    },
  })
}
```

**Comment by Gautamsiva** [comment]
> Hey @ViktorQvarfordt,
> 
> by default, next js does not seem to process the query string at all, but you can access them, when you add `async function getServerSideProps()`. This is also required to make useRouter.query available during SSR. (otherwise pages are statically prerendered, so they can not know about the query string).
> 
> I prefer query params in most cases (thinking about switching to them as a new default in future versions too...) and I think it is also okay to share them with next, in some cases it might even be very useful.
> 
> The lib has a undocumented third parameter (where you can pass the interface to use to get/set the query string), so I was able to quickly put a working demo together:
> https://codesandbox.io/s/github/xiel/use-location-state/tree/nextjs/src/examples/nextjs?file=/pages/index.js
> 
> Please feel free to try it out and let me know if you find problems.
> – Felix
> 
> #### useNextQueryState.js
> ```js
> import { useRouter } from 'next/router'
> import { useQueryState } from 'use-location-state'
> 
> export function useNextQueryState(key, defaultValue) {
>   const router = useRouter()
>   return useQueryState(key, defaultValue, {
>     queryStringInterface: {
>       getQueryString: () => router.asPath.split('?')[1],
>       setQueryString: (newQueryString, { method = 'replace' }) => {
>         router[method](router.pathname + '?' + newQueryString)
>       },
>     },
>   })
> }
> ```

what if i have to do the same for a dynamic link?
