### ISSUE TITLE
Allow null values

### ISSUE THREAD

**Issue by afk-mario** [xiel/use-location-state#134]
It would be nice if variable of state is null, then remove the query string from the URL

**Comment by xiel** [comment]
Hi @afk-mario 

may I asked for a code snipped what you tried already? And what is the current behaviour you are getting?

Because this should work already. You might get a type-error from TypeScript? Can you add a ts-ignore and try?
`setName(null)` should reset to the initial value and remove the entry from the query string.

– Felix

**Comment by xiel** [comment]
@afk-mario Thank you for opening this ticket.

This new feature is released with version [v2.5.0](https://github.com/xiel/use-location-state/releases/tag/2.5.0)
